"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const logger_service_1 = require("./base/logger.service");
const inquirer_service_1 = require("./base/inquirer.service");
const setup_service_1 = require("./services/setup.service");
const index_1 = require("./reader/index");
const FindNgForWithoutTrackByCallbackJob_1 = require("./jobs/FindNgForWithoutTrackByCallbackJob");
const loggerService = logger_service_1.LoggerService.getInstance(logger_service_1.LogLevel.DEBUG);
const inquiryService = inquirer_service_1.InquiryService;
const setupService = setup_service_1.SetupService.getInstance(loggerService);
setupService.initialize();
const reader = index_1.Reader.getInstance([new FindNgForWithoutTrackByCallbackJob_1.FindNgForWithoutTrackByCallbackJob({ skipCommented: true })], loggerService);
console.log("🚀 ~ reader:", reader);
const result = reader.scan('/path/to/directory');
console.log(result);
